### ISSUE TITLE
Cannot read property of 'client' of undefined!

### ISSUE THREAD

**Issue by TheSwindler44** [samc621/SneakerBot#18]
Any suggestions on how to correct this error?

![error_1](https://user-images.githubusercontent.com/36936042/115130657-72e34900-9fbf-11eb-8435-1b902c43851e.JPG)
![error_2](https://user-images.githubusercontent.com/36936042/115130659-72e34900-9fbf-11eb-89cf-5ba922534b9b.JPG)

I've executed `knex migrate:latest` and `knex seed:run` without any problems. I run into the problem when running `docker run -p 5900:5900 -p 8000:8000 --env-file .env.docker sneakerbot` or `TASK_ID=2 CARD_FRIENDLY_NAME=Vista node ./scripts/start-task.js`. 

My environment file name is env.docker and I've quadruple checked to ensure it is parsed correctly. I've also executed the command `export NODE_ENV=docker` before attempting the commands above. 

P.S.: If I run `npm start` I get `App listening on port 8000`. No log file is being created in the directory. This PS section may be unimportant but just letting you know. 

Any help is appreciated.

**Comment by amad1101** [comment]
I am having similar issue with docker-compose. I am getting the following
`KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
`
I am on the latest ubuntu.

**Comment by samc621** [comment]
Hi @TheSwindler44, unfortunately, `export NODE_ENV=docker` won't set the `NODE_ENV` in the docker container. So I think I will need to add `--env NODE_ENV=docker` to the `docker run` script. I've added that [here](https://github.com/samc621/SneakerBot/commit/7597530b8707fb03c2b93780365a2c7e3d1a09c5).

I hadn't encountered this because I have mainly been running it with Docker Compose. Thank you for opening this issue!

**Comment by samc621** [comment]
Hi @amad1101 when running this with Docker Compose, `knex` will use the DB configuration in `.env.docker`. Can you ensure that you've set the right DB host and port? The `DB_HOST` should be `postgres` since Docker-Compose can recognize that name as an alias for the `postgres` service (within the same network). And the `DB_PORT` should be `5432` (the default set by Postgresql). The `DB_USERNAME`, `DB_PASSWORD`, and `DB_NAME` should match what's set in the `environment` under the `postgres` service in `docker-compose.yml`.

**Comment by samc621** [comment]
I have added some more instructions about env configuration with this [commit](https://github.com/samc621/SneakerBot/commit/349e1e3b4bc1d8346b195057a24431d55d75b965), and am now closing this issue. Feel free to open a new ticket if any issues persist.
